INPUT_LAYER = 19
BOARD_ROWS = 10
BOARD_COLS = 9
BOARD_AREA  =BOARD_ROWS * BOARD_COLS
ACTION_PROB = 192


RED_PLAYER_NUM = 1
BLACK_PLAYER_NUM = -1
CHESS_WIDTH = 80
CHESS_HEIGHT= 80   
CHESS_TYPE = [1,2,3,4,5,6,7]#King，mandarin,elephant,knight,rook,cannon,pawn
